name: appproject1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  avatar_glow: ^3.0.1
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.1.2
  lottie: ^2.7.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.2
  firebase_core: 2.24.2
  firebase_messaging: 14.7.9
  flutter: 
    sdk: flutter
  timelines: ^0.1.0
  intl: ^0.19.0
  url_launcher: ^6.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/icon/
    - assets/logo/
  uses-material-design: true

